# docker-compose.yml

version: '3.8' # Docker Compose sürümü

services:
  # -----------------------------------------
  # PHP Servisi (Laravel Uygulamanız)
  # -----------------------------------------
  app:

    build:
      context: .
      dockerfile: Dockerfile
    container_name: tashih_app
    restart: unless-stopped
    working_dir: /var/www/html

    volumes:
      - ./:/var/www/html

    # Ağ Ayarları
    networks:
      - tashih_network
      - mariadb_default


  # -----------------------------------------
  # Nginx Servisi (Web Sunucusu)
  # -----------------------------------------
  web:
    image: nginx:alpine # Hazır Nginx imajını kullan (küçük boyutlu alpine sürümü)
    container_name: tashih_web # Konteynere verilecek isim
    restart: unless-stopped    # Otomatik yeniden başlatma ayarı
    ports:
      - "8080:80"

    # Volume'lar
    volumes:
      - ./:/var/www/html
      # Projedeki Nginx konfigürasyon dosyasını konteyner içine bağla (read-only)
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    # Ağ Ayarları
    networks:
      # PHP servisi ile aynı ağa bağla
      - tashih_network

    # Bağımlılıklar (İsteğe Bağlı)
    depends_on:
      # 'app' servisinin başlamasını bekler (tamamen hazır olmasını garantilemez)
      - app

# -----------------------------------------
# Ağ Tanımlamaları
# -----------------------------------------
networks:
  tashih_network:
    driver: bridge
  # --- BU BÖLÜMÜ GÜNCELLEYİN/EKLEYİN ---
  mariadb_default: # Bulduğumuz ağ adını kullanıyoruz
    external: true # Bu ağın zaten var olduğunu belirtir
